name: spinnet_cuda12
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.9.25
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - addict==2.4.0
    - asttokens==3.0.1
    - attrs==25.4.0
    - blinker==1.9.0
    - certifi==2026.1.4
    - charset-normalizer==3.4.4
    - click==8.1.8
    - comm==0.2.3
    - configargparse==1.7.1
    - contourpy==1.3.0
    - cycler==0.12.1
    - dash==3.3.0
    - debugpy==1.8.19
    - decorator==5.2.1
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - filelock==3.19.1
    - flask==3.1.2
    - fonttools==4.60.2
    - fsspec==2025.10.0
    - idna==3.11
    - importlib-metadata==8.7.1
    - importlib-resources==6.5.2
    - ipykernel==6.31.0
    - ipython==8.18.1
    - ipywidgets==8.1.8
    - itsdangerous==2.2.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.3
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter-client==8.6.3
    - jupyter-core==5.8.1
    - jupyterlab-widgets==3.0.16
    - kiwisolver==1.4.7
    - markupsafe==2.1.5
    - matplotlib==3.9.4
    - matplotlib-inline==0.2.1
    - mpmath==1.3.0
    - narwhals==2.15.0
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - numpy==2.0.2
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - open3d==0.19.0
    - packaging==25.0
    - pandas==2.3.3
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==11.3.0
    - platformdirs==4.4.0
    - plotly==6.5.1
    - pointnet2-ops==3.0.0
    - prompt-toolkit==3.0.52
    - protobuf==6.33.3
    - psutil==7.2.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pygments==2.19.2
    - pyparsing==3.3.1
    - pyquaternion==0.9.9
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - referencing==0.36.2
    - requests==2.32.5
    - retrying==1.4.2
    - rpds-py==0.27.1
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - six==1.17.0
    - stack-data==0.6.3
    - sympy==1.13.1
    - tensorboardx==2.6.4
    - threadpoolctl==3.6.0
    - torch==2.5.1+cu121
    - torchaudio==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - tornado==6.5.4
    - tqdm==4.67.1
    - traitlets==5.14.3
    - triton==3.1.0
    - typing-extensions==4.15.0
    - tzdata==2025.3
    - urllib3==2.6.3
    - wcwidth==0.2.14
    - werkzeug==3.1.5
    - widgetsnbextension==4.0.15
    - zipp==3.23.0
prefix: /users/Etu0/21400500/.conda/envs/spinnet_cuda12
